
package com.synergyj.webservices.lab.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConversorTemperaturasServiceImplService", targetNamespace = "http://sib.webservices.cursos.synergyj.com/", wsdlLocation = "http://127.0.0.1:9878/conversorTemperaturasService?wsdl")
public class ConversorTemperaturasServiceImplService
    extends Service
{

    private final static URL CONVERSORTEMPERATURASSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.synergyj.webservices.lab.cliente.ConversorTemperaturasServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.synergyj.webservices.lab.cliente.ConversorTemperaturasServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:9878/conversorTemperaturasService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:9878/conversorTemperaturasService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONVERSORTEMPERATURASSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ConversorTemperaturasServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConversorTemperaturasServiceImplService() {
        super(CONVERSORTEMPERATURASSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://sib.webservices.cursos.synergyj.com/", "ConversorTemperaturasServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns ConversorTemperaturasService
     */
    @WebEndpoint(name = "ConversorTemperaturasServiceImplPort")
    public ConversorTemperaturasService getConversorTemperaturasServiceImplPort() {
        return super.getPort(new QName("http://sib.webservices.cursos.synergyj.com/", "ConversorTemperaturasServiceImplPort"), ConversorTemperaturasService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConversorTemperaturasService
     */
    @WebEndpoint(name = "ConversorTemperaturasServiceImplPort")
    public ConversorTemperaturasService getConversorTemperaturasServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sib.webservices.cursos.synergyj.com/", "ConversorTemperaturasServiceImplPort"), ConversorTemperaturasService.class, features);
    }

}
